### ISSUE TITLE
请教您关于SCAD惩罚函数用Python实现的问题

### ISSUE THREAD

**Issue by mookixiao** [jeremy-feng/statistical-data-analysis-method-coursework#4]
您好，

导师让我用Python复现《Variable Selection via Nonconcave Penalized Likelihood and its Oracle Properties》

查资料找到您的这篇文章https://fengchao.pro/blog/variable-selection-via-nonconcave-penalized-likelihood/，但是里面的实现是R语言版本的，我目前在写Python版本的SCAD惩罚函数时遇到了一些问题。

冒昧请问下能否请教您一下？如果方便的话请问可以给一个可以联系到您的邮箱吗？您网站上的2022210690089@m.fudan.edu.cn这个邮箱不能发送邮件了

如有打扰，万分抱歉，谢谢

**Comment by jeremy-feng** [comment]
你好，你在博客上看到的邮箱可以直接点击“联系”按钮的，我想你可能是右键点击了“复制电子邮件地址”，导致前面多了一个`%20`。正确的邮箱是 `22210690089@m.fudan.edu.cn`。

关于用 Python 而不是 R 语言实现的问题，你也可以问问 GPT 试试～当然也欢迎和我交流！
